/**
 * Generates src/shared/ui/styles/tokens.css from tokens.json (Osnova design system).
 * tokens.json is the source of truth; never edit tokens.css by hand.
 *
 *   npm run tokens
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

type ThemedValue = string | Record<string, string>
type Token = { name: string; value: ThemedValue; usage?: string }
type TextStyle = {
  name: string
  fontSize: string
  lineHeight: string
  fontWeight: number | string
  letterSpacing?: string
}
type Tokens = {
  color: { themes: { id: string }[]; tokens: Token[] }
  type: {
    families: Record<string, string>
    groups: { family: string; styles: TextStyle[] }[]
  }
  [family: string]: unknown
}

const SOURCE = new URL('../src/shared/ui/styles/tokens.json', import.meta.url)
const TARGET = new URL('../src/shared/ui/styles/tokens.css', import.meta.url)
const SCALAR_FAMILIES = ['spacing', 'radius', 'shadow', 'size', 'breakpoint', 'zIndex']

const tokens = JSON.parse(readFileSync(SOURCE, 'utf8')) as Tokens
const [primaryTheme, ...otherThemes] = tokens.color.themes.map((t) => t.id)

/** CSS custom property name; dots must be escaped (`space-0.5` → `--space-0\.5`). */
const prop = (name: string) => `--${name.replace(/\./g, '\\.')}`
/** `{slate-800}` aliases become `var(--slate-800)`. */
const resolve = (value: string) =>
  value.replace(/\{([^}]+)\}/g, (_, ref: string) => `var(${prop(ref)})`)
const valueFor = (value: ThemedValue, theme: string) =>
  typeof value === 'string' ? (theme === primaryTheme ? value : undefined) : value[theme]

const scalarTokens = SCALAR_FAMILIES.flatMap(
  (family) => (tokens[family] as { tokens?: Token[] } | undefined)?.tokens ?? []
)
const themedTokens = [...tokens.color.tokens, ...scalarTokens]

const declarations = (theme: string, indent = '  ') =>
  themedTokens
    .map((t) => [t.name, valueFor(t.value, theme)] as const)
    .filter((entry): entry is readonly [string, string] => entry[1] !== undefined)
    .map(([name, value]) => `${indent}${prop(name)}: ${resolve(value)};`)

const fontFamilies = Object.entries(tokens.type.families).map(
  ([name, stack]) => `  --font-${name}: ${stack};`
)

const textStyles = tokens.type.groups.flatMap((group) =>
  group.styles.map((s) =>
    [
      `.os-text-${s.name} {`,
      `  font-family: var(--font-${group.family});`,
      `  font-size: ${s.fontSize};`,
      `  line-height: ${s.lineHeight};`,
      `  font-weight: ${s.fontWeight};`,
      s.letterSpacing ? `  letter-spacing: ${s.letterSpacing};` : undefined,
      '}'
    ]
      .filter(Boolean)
      .join('\n')
  )
)

const blocks = [
  '/* GENERATED by scripts/build-tokens.ts from tokens.json. Do not edit by hand. */',
  `:root,\n[data-theme='${primaryTheme}'] {\n${[...fontFamilies, ...declarations(primaryTheme)].join('\n')}\n}`,
  ...otherThemes.flatMap((theme) => {
    const body = declarations(theme)
    return [
      `[data-theme='${theme}'] {\n${body.join('\n')}\n}`,
      `@media (prefers-color-scheme: ${theme}) {\n  :root:not([data-theme]) {\n${declarations(theme, '    ').join('\n')}\n  }\n}`
    ]
  }),
  ...textStyles
]

writeFileSync(TARGET, `${blocks.join('\n\n')}\n`)
console.log(`tokens.css written (${themedTokens.length} tokens) → ${fileURLToPath(TARGET)}`)
