<template>
  <svg
    width="112"
    height="114"
    viewBox="0 0 112 114"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    class="section-card-img"
    data-astro-cid-j7pv25f6=""
  >
    <rect width="58" height="58" rx="5" fill="var(--background)" data-astro-cid-j7pv25f6=""></rect>
    <rect
      x="69"
      y="25"
      width="33"
      height="33"
      rx="5"
      fill="var(--accent)"
      fill-opacity="0.6"
      data-astro-cid-j7pv25f6=""
    ></rect>
    <rect
      x="69"
      y="71"
      width="43"
      height="43"
      rx="5"
      fill="var(--text)"
      fill-opacity="0.1"
      data-astro-cid-j7pv25f6=""
    ></rect>
    <rect
      x="20"
      y="70"
      width="38"
      height="39"
      rx="5"
      fill="var(--text)"
      data-astro-cid-j7pv25f6=""
    ></rect>
  </svg>
</template>
